name: Tag and publish changelog

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: release with changelog
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - uses: astral-sh/setup-uv@v5

      - uses: cocogitto/cocogitto-action@v3
        name: release
        id: release
        with:
          release: true

      - name: github changelog
        run: >
          cog changelog
          --at ${{ steps.release.outputs.version }}
          --template full_hash > ${{ github.workspace }}-CHANGELOG.md

      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
